[project]
name = "ocr-research"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "google-genai>=1.9.0",
    "streamlit-pdf-viewer>=0.0.22",
    "streamlit>=1.44.1",
    "watchdog>=6.0.0",
]
